language: generic
sudo: required
services:
  - docker

before_install:
  - docker build --t SomyaAgrawal13/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true SomyaAgrawal13/docker-react npm run test 